server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/onmuseum
    username: sa
    password:
    driver-class-name: org.h2.Driver

  thymeleaf:
    enabled: true
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernates:
        show_sql: true
        format_sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
